FROM bitwalker/alpine-elixir:1.9.4

RUN apk update && \
    apk --no-cache --update add libgcc libstdc++ && \
    rm -rf /var/cache/apk/*

EXPOSE 4000
ENV PORT=4000 MIX_ENV=prod REPLACE_OS_VARS=true SHELL=/bin/sh

ADD ${APP}.tar.gz ./
RUN chown -R default ./releases

USER root

ENTRYPOINT ["/opt/app/bin/${APP}"]
